### ISSUE TITLE
env files

### ISSUE THREAD

**Issue by gossie** [sengsei/spring-boot-react-bundle#7]
Du hast drei .env Dateien, .env.development, .env.test und .env.production. In der .env.development hast du die Variable `REACT_APP_DEV_URL`, in der .env.test `REACT_APP_DEV_TEST` und in .env.production `REACT_APP_PROD-URL`. Das macht so keinen Sinn. Dann müsstest du in deinem Code ja wieder irgendwie unterscheiden welche Variable eingelesen wird. In allen Dateien sollten sie den gleichen Namen, aber unterschiedliche Werte haben.

**Comment by sengsei** [comment]
fixed
